# Generated by Django 5.0.4 on 2024-05-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribtionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('days', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscribtiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('name_on_card', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv_code', models.CharField(max_length=4)),
                ('subsribe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.subsribe')),
            ],
        ),
    ]
