# Generated by Django 5.0.4 on 2024-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribtiontype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
