# Generated by Django 5.0.1 on 2024-04-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summarized_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='complexity_level',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
    ]
