# Generated by Django 5.0.1 on 2024-04-23 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_rename_summarized_text_summary_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),  # Default to user ID 1
            preserve_default=False,
        ),
    ]

