# Generated by Django 5.0.1 on 2024-04-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_alter_summary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.document'),
        ),
    ]
