# Generated by Django 5.0.1 on 2024-04-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_remove_summary_updated_at_summary_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.AlterField(
            model_name='summary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='summary.document'),
        ),
    ]
