# Generated by Django 5.0.1 on 2024-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_alter_summary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
    ]
