# Generated by Django 5.0.1 on 2024-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_summary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='complexity_level',
            field=models.CharField(choices=[('main_points', 'Main Points'), ('detailed', 'Detailed')], default='main_points', max_length=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
